
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-19T14:33:09-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a69e540539f96e37469bfdf42830b1eaeafbed06",
 "version": "1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
